['vert_pl_slopes', 'Ухили вертикального планування', 'LineString']

['local_power_lines', 'Лінії місцевих електромереж', 'LineString']
['main_power_lines', 'Магістральні лінії електропередачі', 'LineString']
['local_gas_pipes', 'Розподільні газопроводи', 'LineString']  
['main_gas_pipes', 'Магістральні газопроводи', 'LineString']  
['local_telecom_lines', 'Лінії місцевих телекомунікаційних мереж', 'LineString']
['main_telecom_lines', 'Магістральні телекомунікаційні лінії', 'LineString']
['water_supply', 'Місцеві водопроводи питного водопостачання', 'LineString']
['water_tech_supply', 'Місцеві водопроводи технічного водопостачання', 'LineString']
['main_water_pipes', 'Магістральні водопроводи', 'LineString']
['rain_water_sewer', 'Трубопроводи дощової каналізації', 'LineString']
['heating_pipes', 'Місцеві мережі теплопостачання', 'LineString']
['main_oil_pipes', 'Магістральні нафтопроводи', 'LineString'] 
['main_products_pipes', 'Продуктопроводи', 'LineString']      

['main_melioration_nets', 'Канали магістральних меліоративних систем', 'LineString']

['forest_roads', 'Польові та лісові дороги', 'LineString']    
['spec_roads', 'Спеціалізовані дороги та проїзди', 'LineString']
['bridge_objects_l', "Об'єкти мостових переходів та шляхопроводів", 'LineString']
['roads', 'Автомобільні дороги', 'LineString']
['trails', 'Мережа доріжок', 'LineString']
['streets', 'Вулиці та дороги населених пунктів', 'LineString']
['trolleybus_lines', 'Тролейбусні лінії', 'LineString']       
['transport_corridors', 'Транспортні коридори', 'LineString'] 
['railways_local', 'Залізниці місцеві', 'LineString']
['railways_main', 'Залізниці магістральні', 'LineString']     

['evacuation_paths', 'Маршрути евакуації населення', 'LineString']
['public_transport_routes', 'Маршрути громадського транспорту', 'LineString']

['tunnel_objects_l', "Об'єкти тунелів", 'LineString']
['thresholds', "Характерні відстані (якісні пороги) видового розкриття пам'яток архітектури", 'LineString']
['str_hydro_l', 'Гідроінженерні споруди', 'LineString']       
['sewerage', 'Трубопроводи каналізаційних мереж', 'LineString']
['river', 'Водотоки', 'LineString']
['review_axes', 'Оглядові осі', 'LineString']
['planning_forms', 'Планувальні утворення в населених пунктах', 'LineString']
['env_protect_meas_l', 'Лінії проведення заходів з охорони довкілля', 'LineString']
['eng_protect_measures_l', 'Лінійна локалізація заходів із захисту території від небезпечних природних процесів', 'LineString']
['compos_axes', 'Планувально-композиційні осі', 'LineString'] 
['chemical_hazad_line_objects', "Хімічно небезпечні об'єкти лінійної протяжності", 'LineString']
['roundabout_paths', 'Напрямки обходів у випадку руйнування основних шляхопроводів', 'LineString']
['tour_routes', 'Туристичні маршрути', 'LineString']
['review_fronts', 'Оглядові фронти', 'LineString']
['planning_axes', 'Планувальні вісі', 'LineString']
['countur', 'Горизонталі', 'LineString']

['eng_protect_other_l', 'Інші проектні заходи з інженерної підготовки та захисту території', 'LineString']