['winter_resourts', 'Комплекси зимових видів спорту', 'Point']
['water_transport', "Об'єкти водного транспорту", 'Point']    
['urban_space_types', 'Характерні типи міських просторів', 'Point']
['unesco_nature_p', "Природні об'єкти всесвітньої спадщини ЮНЕСКО", 'Point']
['tunnel_objects_p', 'Локалізація тунелів', 'Point']
['trollyebus_service', "Об'єкти обслуговування тролейбусних ліній", 'Point']
['transport_enterprises', 'Транспортні підприємства', 'Point']
['techservice_stations', 'Станції технічного обслуговування', 'Point']
['str_hydro_p', 'Гідроінженерні споруди', 'Point']
['storage_objects', "Складські об'єкти", 'Point']
['sport_fishery_objects', "Об'єкти любительського і спортивного рибальства", 'Point']
['sewerage_objects', "Об'єктинa каналізаційних мережах", 'Point']
['sew_treat_plants', 'Каналізаційні очисні споруди', 'Point'] 
['runway_service', "Об'єкти обслуговування злітно-посадкових смуг", 'Point']
['review_point', 'Оглядові точки', 'Point']
['resort_objects', 'Санаторно-курортні та оздоровчі заклади', 'Point']
['recultivation_allocation', 'Місця рекультивації порушених територій', 'Point']
['railways_obj', "Об'єктинa залізничних мережах", 'Point']    
['rail_transport', "Об'єкти залізничних перевезень", 'Point'] 
['public_transport_stops', 'Зупинки громадського транспорту', 'Point']
['public_toilets', 'Громадські туалети', 'Point']
['product_pipes_objects', "Об'єктинa продуктопроводах", 'Point']
['potent_hazard_objects', "Потенційно небезпечні об'єкти (ПНО)", 'Point']
['pollution_objects', 'Основні забруднювачі', 'Point']        
['plant_cultivation_objects', 'Підприємства рослинництва', 'Point']
['planning_centres', 'Планувальні центри', 'Point']
['petrol_stations', 'Автозаправочні станції', 'Point']        
['objects_banks', 'Фінансові установи', 'Point']
['natural_hazards_points', 'Локалізація небезпечних природних процесів', 'Point']
['named_ob', "Поіменовані адресні об'єкти", 'Point']
['meteostations', 'Основні метеостанції державної мережі спостережень', 'Point']
['main_water_objects', "Об'єктинa магістральних водопроводах", 'Point']
['logistic_centres', 'Логістичні центри', 'Point']
['local_water_objects', "Об'єкти місцевих водопровідних мереж питного водопостачання", 'Point']
['local_techwater_objects', "Об'єкти місцевих водопровідних мереж технічного водопостачання", 'Point']
['livestock_objects', 'Підприємства тваринництва', 'Point']   
['hunting_objects', "Мисливські об'єкти", 'Point']
['hotels', 'Заклади короткострокового проживання', 'Point']   
['high_hazard_objects', "Об'єкти підвищенної небезпеки (ОПН)", 'Point']
['heritage_monuments', "Пам'ятки культурної спадщини", 'Point']
['heating_objects', "Об'єктинa мережах теплопостачання", 'Point']
['garages', 'Гаражі', 'Point']
['forestery_objects', "Лісогоподарські об'єкти", 'Point']     
['fishery_objects', 'Рибницькі підприємства', 'Point']        
['fire_wat_intake_place_p', 'Розміщення облаштованих місць забору води для потреб пожежогасіння', 'Point']
['fire_reservoirs_p', 'Розміщення водойм для гасіння пожеж (штучні)', 'Point']
['evacuation_points', 'Пункти евакуації', 'Point']
['evac_pop_distrib_points', 'Пункти розміщення евакуйованого/ відселеного населення', 'Point']
['env_protect_meas_p', 'Локалізація проведення заходів з охорони довкілля', 'Point']
['env_monitoring_p', 'Пункти моніторингу стану довкілля', 'Point']
['env_conflict_res_p', 'Вузли вирішення можливих конфліктів господарської діяльності та збереження довкілля', 'Point']      
['eng_protect_other_p', 'Інші проектні заходи з інженерної підготовки та захисту території', 'Point']
['eng_protect_measures_p', 'Локалізація заходів із захисту території від небезпечних природних процесів', 'Point']
['dominant_build', 'Містобудівні домінанти (визначні споруди)', 'Point']
['disharmony', 'Дисгармонійні (дисонуючі) будівлі та споруди', 'Point']
['crematoria', 'Крематорії', 'Point']
['compos_nodes', 'Планувально-композиційні вузли', 'Point']   
['communication_objects', "Об'єкти зв'язкунa трубопроводах", 'Point']
['civil_protect_constr_p', 'Розташування захисних споруд цивільного захисту', 'Point']
['chem_hazad_point_objects', "Хімічно небезпечні об'єкти з точковим джерелом забруднення", 'Point']
['auto_transport', "Об'єкти автотранспортних перевезень", 'Point']
['address', 'Адреси', 'Point']
['ammunition_stores', 'Склади військового озброєння (засобів ураження)', 'Point']
['animal_burial_grounds', 'Місця захоронення трупів тварин', 'Point']
['animal_shelters', 'Притулки для тварин', 'Point']
['beach_objects', 'Пляжі', 'Point']
['cemeteries', 'Кладовища', 'Point']
['avia_transport', "Об'єкти повітряних перевезень", 'Point']  
['car_park', 'Автостоянки для постійного зберігання автомобілів', 'Point']
['bridge_objects_p', 'Локалізація мостових переходів та шляхопроводів', 'Point']
['autoservices', 'Пункти сервісунa автошляхах (комплекси автосервісу)', 'Point']
['civil_protect_objects_p', "Розташування об'єктів, що належать до категорій з цивільного захисту", 'Point']
['crossborder', 'Пункти пропуску через державний кордон', 'Point']
['garbage_grounds', 'Місця видалення відходів', 'Point']      
['gas_pipes_objects', "Об'єктинa газопроводах", 'Point']      
['geodetic_points', 'Геодезичні пункти', 'Point']
['green_p', "Об'єкти озеленення", 'Point']
['transport_storage', 'Транспортно-складські комплекси', 'Point']
['telecom_objects', "Телекомунікаційні об'єкти", 'Point']     
['ritual_services', 'Організації з надання ритуальних послуг', 'Point']
['reserves_stores', 'Бази та склади матеріально-технічних, продовольчих та інших резервів', 'Point']
['recycling_object', 'Підприємства поводження з відходами', 'Point']
['rain_sewer_objects', "Об'єкти дощової каналізації", 'Point']
['pzf_p', "Об'єкти природно-заповідного фонду", 'Point']      
['power_objects', "Об'єкти систем електрозабезпечення", 'Point']
['objects_catering', 'Заклади громадського харчування', 'Point']
['np_in_catastr_flood_areas', 'Населені пункти в зоні можливого катастрофічного затоплення у разі руйнування гребель', 'Point']
['minerals_p', 'Родовища корисних копалин', 'Point']
['lost_objects', "Значні втрачені об'єкти", 'Point']
['industry_objects', 'Промислові підприємства', 'Point']      
['housing_offices', 'Житлово-експлуатаційні організації', 'Point']
['trucks_grounds', 'Майданчики для відстою вантажного автотранспорту', 'Point']
['terminals', 'Термінали', 'Point']
['ref_point', 'Опорні точки', 'Point']
['power_plants', 'Електростанції', 'Point']
['objects_research', 'Науково-дослідні, проектні та вишукувальні заклади', 'Point']
['objects_culture', "Об'єкти культури та мистецтва", 'Point']      
['injured_med_help_points', 'Пункти надання необхідної медичної допомоги постраждалим', 'Point']
['innovative_objects', "Інноваційно-виробничі об'єкти", 'Point']
['interchange', "Транспортна розв'язка", 'Point']
['intern_wetlands_p', 'Водно-болотні угіддя, що мають міжнародне значення', 'Point']
['objects_education', 'Освітні заклади', 'Point']
['objects_home_service', 'Заклади побутового обслуговування', 'Point']
['objects_medical', "Заклади охорони здоров'я", 'Point']      
['objects_monuments', 'Монументи, скульптури', 'Point']       
['objects_pharmacy', 'Фармацевтичні заклади', 'Point']        
['objects_public', 'Адміністративно-управлінські заклади', 'Point']
['objects_religious', "Культові об'єкти", 'Point']
['objects_social_protect', 'Заклади соціального захисту населення', 'Point']
['objects_sport', "Спортивні об'єкти", 'Point']
['objects_trade', 'Заклади торгівлі', 'Point']
['objects_veterinary', 'Ветеринарні лікарні', 'Point']        
['oil_pipes_objects', "Об'єктинa нафтопроводах", 'Point']     
['other_agro_objects', "Інші сільськогосподарські об'єкти", 'Point']