['protect_zones', 'Охоронні зони', 'Polygon']
['sanit_protect_zones', 'Санітарно-захисні зони', 'Polygon']  
['sanit_gaps', "Санітарні відстані (розриви) від об'єкту", 'Polygon']
['areas_in_red_lines', 'Території в червоних лініях', 'Polygon']
['building_reg_lines', 'Території в лініях регулювання забудови', 'Polygon']
['areas_in_blue_lines', 'Території в блакитних лініях', 'Polygon']
['areas_in_green_lines', 'Території в зелених лініях', 'Polygon']
['areas_in_yellow_lines_pg', 'Території в жовтих лініях', 'Polygon']
['world_heritage_buf', "Буферні зони об'єктів всесвітньої спадщини", 'Polygon']
['waterprotect_zones', 'Водоохоронні зони', 'Polygon']        
['pzf_protected_zones', "Охоронні зони об'єктів природно-заповідного фонду", 'Polygon']


['str_engineering', 'Будівлі та споруди інженерного забезпечення', 'Polygon']
['str_grounds', 'Функціональні майданчики', 'Polygon']        
['str_hydro_pg', 'Гідроінженерні споруди', 'Polygon']
['str_industrial', 'Виробничі будівлі та споруди', 'Polygon'] 
['str_other', 'Інші будівлі та споруди', 'Polygon']
['str_public', 'Громадські будівлі та споруди', 'Polygon']    
['str_residential', 'Житлові будівлі', 'Polygon']
['str_restrict', 'Спеціалізовані споруди', 'Polygon']
['str_transport', 'Будівлі та споруди транспорту', 'Polygon'] 




['dpt_area', 'Територія,нa яку розроблено ДПТ', 'Polygon']    


['green_pg', 'Озеленення', 'Polygon']
['agro_landscape_groups', 'Агроландшафтні групи земель', 'Polygon']
['agro_soil', 'Агровиробничі групи ґрунтів', 'Polygon']       
['ammunition_stores_impact_zones', 'Зона можливого ураження у випадку надзвичайної ситуаціїнa складах боєприпасів', 'Polygon']
['archeolog_protect_ter', 'Охоронювані археологічні території', 'Polygon']
['avia_limits', 'Авіаційні, радіолокаційні обмеження', 'Polygon']
['bank_protect', 'Прибережні захисні смуги', 'Polygon']       
['beach_zones', 'Пляжні зони', 'Polygon']
['canals_bands', 'Смуги відведення гідротехнічних споруд', 'Polygon']
['catastrophic_flood_areas', 'Зони можливого катастрофічного затоплення у разі руйнування гребель', 'Polygon']
['chem_point_obj_pollut_hazad_areas', 'Зона можливого хімічного забруднення від точкового ХНО', 'Polygon']
['chemical_line_hazad_areas', 'Зона можливого хімічного забруднення від ХНО лінійної протяжності', 'Polygon']
['city_district', 'Райони у містах', 'Polygon']
['civil_protect_constr_pg', 'Захисні споруди цивільного захисту', 'Polygon']
['civil_protect_objects_pg', "Об'єкти, що належать до категорій з цивільного захисту", 'Polygon']
['climate', 'Поширення кліматичних показників', 'Polygon']
['degraded_soils', 'Ареали поширення деградованих та еродованих ґрунтів', 'Polygon']
['disturbed_areas', 'Порушені території', 'Polygon']
['econet', 'Структурні елементи екологічної мережі', 'Polygon']
['ecovillage', 'Території екопоселень', 'Polygon']
['education_zones', 'Зони обслуговування освітніми закладами', 'Polygon']
['emerald_network', 'Території Смарагдової мережі', 'Polygon']
['eng_protect_measures_pg', 'Ареали реалізації заходів із захисту території від небезпечних природних процесів', 'Polygon'] 
['eng_protect_other_pg', 'Інші проектні заходи з інженерної підготовки та захисту території', 'Polygon']
['env_aim', 'Оцінювання пріоритетності використання та охорони довкілля', 'Polygon']
['env_conflict_res_pg', 'Зони вирішення можливих конфліктів господарської діяльності та збереження довкілля', 'Polygon']    
['env_monitoring_pg', 'Ареали моніторингу стану довкілля', 'Polygon']
['env_protect_meas_pg', 'Території проведення заходів з охорони довкілля', 'Polygon']
['evac_pop_distrib_areas', 'Території розміщення населення, евакуйованого із зони можливих сильних руйнувань', 'Polygon']   
['expropriat_areas', "території, до складу яких входять земельні ділянки, необхідні для розміщення об'єктів, щодо яких відповідно до закону може здійснюватися примусове відчуження земельних ділянок з мотивів суспільної необхідності", 'Polygon']    
['fire_reservoirs_pg', 'Водойми для гасіння пожеж (штучні)', 'Polygon']
['fire_stations', 'Пожежно-рятувальні підрозділи', 'Point']   
['fire_wat_intake_place_pg', 'Облаштовані місця забору води для потреб пожежогасіння', 'Polygon']
['forest_belts', 'Лісосмуги', 'Polygon']
['free_econom_zones', 'Вільні економічні зони', 'Polygon']    
['function_zoning_in', 'Функціональне використання територій існуюче', 'Polygon']
['function_zoning_pr', 'Функціональне призначення територій проектне', 'Polygon']
['hazard_radioact_pollut', 'Зони можливого небезпечного радіоактивного забруднення', 'Polygon']
['health_protect_zones', 'Зони санітарної охорони курортів', 'Polygon']
['heritage_mon_areas', "Визначні місця - пам'ятки культурної спадщини", 'Polygon']
['heritage_protect_zones', "Зони охорони пам'яток культурної спадщини", 'Polygon']
['high_hazard_obj_impact_zone', 'Зона впливу ОПН', 'Polygon'] 
['hist_cult_area', 'Історико-культурні заповідні території', 'Polygon']
['hist_cult_conserv', 'Історико-культурні заповідники', 'Polygon']
['historic_areals', 'Історичні ареали населених місць', 'Polygon']
['historic_build', 'Історична забудова', 'Polygon']
['historic_rajon', 'Історичні райони населеного пункту', 'Polygon']
['hromada', 'Території територіальних громад', 'Polygon']
['intern_wetlands_pg', 'Території водно-болотних угідь, що мають міжнародне значення', 'Polygon']
['invest_areas', 'Інвестиційно привабливі території', 'Polygon']
['land_conservation', 'Консервація земель', 'Polygon']        
['landmanagement', 'Землевпорядні заходи', 'Polygon']
['lands', 'Контури земель', 'Polygon']
['lands_massif', 'Масив земель сільськогосподарського призначення', 'Polygon']
['landscape_assesm', 'Оцінювання ландшафтних умов', 'Polygon']
['landuse', 'Угіддя', 'Polygon']
['landuse_violation', 'Території порушення складу угідь', 'Polygon']
['loess_sediments_pg', 'Розповсюдження лесових порід, що мають властивість до просідання', 'Polygon']
['medical_zones', "Зони обслуговування закладами охорони здоров'я", 'Polygon']
['melioration', 'Території меліорації', 'Polygon']
['minerals_pg', 'Території залягання корисних копалин', 'Polygon']
['mining_allocation', 'Гірничі відводи', 'Polygon']
['mining_spec_permit', 'Спеціальні дозволинa користування надрами', 'Polygon']
['monuments_view_areas', "Зони огляду пам'яток архітектури", 'Polygon']
['natural_hazards_areas', 'Ареали поширення небезпечних природних процесів', 'Polygon']
['nuclear_pollut_zones', 'Зона можливого небезпечного радіоактивного забруднення від АЕС', 'Polygon']
['nuclear_power_plant_control_zones', 'Зони контролю АЕС', 'Polygon']
['parcel', 'Земельна ділянка', 'Polygon']
['pollution_areas', 'Зони забруднення компонентів довкілля', 'Polygon']
['potent_hazard_obj_impact_zone', 'Зона впливу ПНО', 'Polygon']
['pzf_pg', "Території та об'єкти природно-заповідного фонду", 'Polygon']
['pzf_reserve', 'Території, зарезервовані з метою наступного заповідання', 'Polygon']
['pzf_zon', "Зонування територій та об'єктів природно-заповідного фонду", 'Polygon']
['radiactive_limits', 'Радіаційні обмеження', 'Polygon']      
['radionuclide_hazard', 'Зони наднормативних рівнів іонізуючих випромінювань природних радіонуклідів у приміщеннях будівель', 'Polygon']
['recultivation', 'Рекультивація порушених територій', 'Polygon']
['resid_build_shelter_areas', 'Території потенційної організації сховищ та ПРУнa розрахунковий строк у багатоквартирній житловій забудові', 'Polygon']
['safe_areas', 'Безпечні райони', 'Polygon']
['settlement', 'Населені пункти', 'Polygon']
['shore_zones', 'Берегові смуги водних шляхів', 'Polygon']    
['slope', 'Ухили земної поверхні', 'Polygon']
['spec_landuse_zones', 'Зона особливого режиму використання земель', 'Polygon']
['starostynstvo', 'Території старостинських округів', 'Polygon']
['state_reg_interest', 'Території державних та регіональних інтересів', 'Polygon']
['strong_destructions_zones', 'Зони можливих сильних руйнувань', 'Polygon']
['sublease', 'Право суборенди', 'Polygon']
['suburban_zones', 'Приміські зони', 'Polygon']
['support_areas', 'Території, розвиток яких потребує державної підтримки', 'Polygon']
['techno_load', 'Техногенне навантаження', 'Polygon']
['trans_cor_infl_zones', 'Смуги впливу транспортних коридорів', 'Polygon']
['underground_spaces', 'Зони формування підземного простору', 'Polygon']
['unesco_nature_pg', "Території природних об'єктів всесвітньої спадщини ЮНЕСКО", 'Polygon']
['urban_dev_zones', 'Території за ступенем містобудівної цінності', 'Polygon']
['view_zones', 'Зони формування видів', 'Polygon']
['water_supply_protect_zones', 'Зони санітарної охорони джерел водопостачання', 'Polygon']
['waterb', 'Водойми', 'Polygon']
['watershed', 'Водозбірні басейни', 'Polygon']
['weak_destructions_zones', 'Зони можливих слабких руйнувань', 'Polygon']